services:
  - type: web
    name: botonera
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 20
    healthCheckPath: /
